import { PAIR_EVENT_TYPES, type PairEventType } from "./events";
import { PAIR_GROUP_STATES, type PairGroupState } from "./states";

export type PairTransitionDisposition = "LEGAL" | "ILLEGAL";

export interface PairTransitionRule {
  readonly disposition: PairTransitionDisposition;
  readonly note: string;
}

const legalStatesByEvent = {
  PAIR_GROUP_CREATED: [],
  PAIR_CASH_RESERVED: ["SCHEDULED"],
  PAIR_SCHEDULED: ["SCHEDULED"],
  PAIR_ACTIVATION_STARTED: ["SCHEDULED"],
  PAIR_ACTIVATION_REJECTED: ["ACTIVATING"],
  PAIR_ACTIVATION_APPROVED: ["ACTIVATING"],
  PAIR_LEG_PLANNED: ["ACTIVATING", "SUBMITTING"],
  PAIR_LEG_EFFECT_ENQUEUED: ["SUBMITTING"],
  PAIR_LEG_EFFECT_CANCELED_UNCLAIMED: ["SUBMITTING", "OUTCOME_UNKNOWN", "RECONCILING", "MANUAL_REVIEW"],
  PAIR_LEG_EFFECT_EXPIRED_UNCLAIMED: ["SUBMITTING", "OUTCOME_UNKNOWN", "RECONCILING", "MANUAL_REVIEW"],
  PAIR_LEG_DISPATCH_CLAIMED: ["SUBMITTING"],
  PAIR_LEG_RESULT_RECORDED: ["SUBMITTING", "OUTCOME_UNKNOWN", "MANUAL_REVIEW"],
  PAIR_FILL_RECORDED: ["SUBMITTING", "OUTCOME_UNKNOWN", "MANUAL_REVIEW"],
  PAIR_LEG_OUTCOME_UNKNOWN: ["SUBMITTING"],
  PAIR_SERIAL_COMPLEMENT_SCHEDULED: ["SUBMITTING"],
  PAIR_SERIAL_COMPLEMENT_DUE: ["SUBMITTING"],
  PAIR_SERIAL_COMPLEMENT_REJECTED: ["SUBMITTING"],
  PAIR_INVENTORY_RECOMPUTED: ["SUBMITTING", "OUTCOME_UNKNOWN", "PAIRED", "RESIDUAL", "RECOVERING", "RECOVERY_OUTCOME_UNKNOWN", "AWAITING_SETTLEMENT", "MERGE_OUTCOME_UNKNOWN", "AWAITING_RESOLUTION", "RECONCILING", "MANUAL_REVIEW"],
  PAIR_LEG_SKIPPED: ["SUBMITTING", "OUTCOME_UNKNOWN", "RECONCILING"],
  PAIR_CLASSIFIED_NO_INITIAL_FILL: ["SUBMITTING", "OUTCOME_UNKNOWN"],
  PAIR_CLASSIFIED_PAIRED: ["SUBMITTING", "OUTCOME_UNKNOWN", "RECOVERING", "RECOVERY_OUTCOME_UNKNOWN"],
  PAIR_CLASSIFIED_RESIDUAL: ["SUBMITTING", "OUTCOME_UNKNOWN", "RECOVERING", "RECOVERY_OUTCOME_UNKNOWN"],
  PAIR_SETTLEMENT_STARTED: ["PAIRED"],
  PAIR_SETTLEMENT_DEFERRED: ["AWAITING_SETTLEMENT"],
  PAIR_RECOVERY_ALTERNATIVES_CAPTURED: ["RESIDUAL"],
  PAIR_RECOVERY_SKIPPED: ["RESIDUAL"],
  PAIR_RECOVERY_EFFECT_ENQUEUED: ["RESIDUAL", "RECOVERY_PENDING"],
  PAIR_RECOVERY_RESULT_RECORDED: ["RECOVERING", "RECOVERY_OUTCOME_UNKNOWN"],
  PAIR_RECOVERY_OUTCOME_UNKNOWN: ["RECOVERING"],
  PAIR_VIRTUAL_MERGE_ENQUEUED: ["AWAITING_SETTLEMENT"],
  PAIR_VIRTUAL_MERGE_CONFIRMED: ["MERGE_PENDING", "MERGE_OUTCOME_UNKNOWN"],
  PAIR_VIRTUAL_MERGE_FAILED: ["MERGE_PENDING", "MERGE_OUTCOME_UNKNOWN"],
  PAIR_VIRTUAL_MERGE_OUTCOME_UNKNOWN: ["MERGE_PENDING"],
  PAIR_RESOLUTION_APPLIED: ["AWAITING_RESOLUTION", "MANUAL_REVIEW"],
  PAIR_RESERVATION_RELEASED: ["ACTIVATION_REJECTED", "SUBMITTING", "NO_INITIAL_FILL", "PAIRED", "RESIDUAL", "RECOVERY_PENDING", "RECOVERING", "AWAITING_SETTLEMENT", "MERGE_PENDING", "AWAITING_RESOLUTION", "RECONCILING", "MANUAL_REVIEW"],
  PAIR_RECONCILIATION_STARTED: ["ACTIVATION_REJECTED", "OUTCOME_UNKNOWN", "NO_INITIAL_FILL", "RECOVERY_OUTCOME_UNKNOWN", "MERGE_OUTCOME_UNKNOWN", "RECONCILING", "MANUAL_REVIEW"],
  PAIR_PROJECTION_REBUILT: ["RECONCILING", "MANUAL_REVIEW"],
  PAIR_RECONCILIATION_OK: ["RECONCILING"],
  PAIR_RECONCILIATION_MISMATCH: ["OUTCOME_UNKNOWN", "RECOVERY_OUTCOME_UNKNOWN", "MERGE_OUTCOME_UNKNOWN", "RECONCILING"],
  PAIR_HALTED: PAIR_GROUP_STATES.filter((state) => state !== "RECONCILED_FLAT" && state !== "RECONCILED_SETTLED"),
  PAIR_GROUP_CLOSED: ["RECONCILED_FLAT", "RECONCILED_SETTLED"],
} as const satisfies Record<PairEventType, readonly PairGroupState[]>;

export const PAIR_TRANSITION_MATRIX: Readonly<
  Record<PairGroupState, Readonly<Record<PairEventType, PairTransitionRule>>>
> = Object.freeze(Object.fromEntries(PAIR_GROUP_STATES.map((state) => [
  state,
  Object.freeze(Object.fromEntries(PAIR_EVENT_TYPES.map((eventType) => {
    const legal = (legalStatesByEvent[eventType] as readonly PairGroupState[]).includes(state);
    return [eventType, Object.freeze({
      disposition: legal ? "LEGAL" : "ILLEGAL",
      note: legal ? `documented ${state}/${eventType} transition` : `no transition is defined for ${state}/${eventType}`,
    })];
  })) as Record<PairEventType, PairTransitionRule>),
])) as Record<PairGroupState, Readonly<Record<PairEventType, PairTransitionRule>>>);

export function pairTransitionRule(state: PairGroupState, eventType: PairEventType): PairTransitionRule {
  return PAIR_TRANSITION_MATRIX[state][eventType];
}

export function legalPairEventTypes(state: PairGroupState): readonly PairEventType[] {
  return PAIR_EVENT_TYPES.filter((eventType) => PAIR_TRANSITION_MATRIX[state][eventType].disposition === "LEGAL");
}
